### PR TITLE
add fedora-modular-repos as expected package to be installed

### PR DESCRIPTION
**Pull request by bgoncalv**

### CODE REVIEW

**Review by igor-raits — APPROVED** [review]

**Comment by contyk** [comment]
Hmm, the build repo configuration is still included in the image, inside `/etc/dnf/dnf.conf`. If I disable the configuration (`sed 's/enabled=1/enabled=0/' -i /etc/dnf/dnf.conf`), I can still install `dnf` from the `fedora-modular` repo (enabled and provided by `fedora-modular-repos`) but installing additional stuff with dnf just results in `Error: There are no enabled repos.` I'm not sure why that's happening.

**Comment by bgoncalv** [comment]
Hmm, `/etc/dnf/dnf.conf` is created by mock. We can edit the mock root and recreate the file with other settings. Any suggestion what to set as default there?

**Comment by contyk** [comment]
Ok, the dnf issue was caused by `reposdir=/dev/null` in the default `dnf.conf`. Let's replace it with reasonable system defaults and it should be fine.

**Comment by bgoncalv** [comment]
You might need to use the following repo https://kojipkgs.stg.fedoraproject.org/compose/branched/jkaluza/latest-Fedora-Modular-26/compose/Server/x86_64/os/ if fedora-modular-repos is not available yet on our standard repo.

**Comment by mmathesius** [comment]
I was able to get the updates working only after setting "baseurl" in `resources/base-runtime-mock.cfg` to the repo referenced in the previous comment.

**Review by mmathesius — APPROVED** [review]

**Pull request merged**
