### PR TITLE
added testRequiredPackages and testInstalledPackages test cases

### PR DESCRIPTION
**Pull request by bgoncalv**

### CODE REVIEW

**Comment by mmathesius** [comment]
I think the new tests look good.

When running the `smoke.py` script from a fresh checkout, all tests PASS as expected.

Then I made some modifications to the configuration files to remove "curl" from the static list of expected packages, and add "make" to the list of baseimage rpms in a local copy of the modulemd:

```
$ git diff
diff --git a/config.yaml b/config.yaml
index 56a6dae..2728349 100644
--- a/config.yaml
+++ b/config.yaml
@@ -1,7 +1,7 @@
 document: modularity-testing
 version: 1
 name: baseruntime
-modulemd-url: http://pkgs.fedoraproject.org/cgit/modules/base-runtime.git/plain/base-runtime.yaml
+modulemd-url: base-runtime.yaml
 service:
     port:
 packages:
diff --git a/resources/installed_packages/all_installed_pkgs.txt b/resources/installed_packages/all_installed_pkgs.txt
index ee61e4b..7aef1bb 100644
--- a/resources/installed_packages/all_installed_pkgs.txt
+++ b/resources/installed_packages/all_installed_pkgs.txt
@@ -8,7 +8,6 @@ coreutils
 coreutils-common
 cracklib
 crypto-policies
-curl
 cyrus-sasl-lib
 elfutils-libelf
 expat
$ diff -u <(wget -q -O- http://pkgs.fedoraproject.org/cgit/modules/base-runtime.git/plain/base-runtime.yaml) base-runtime.yaml
--- /dev/fd/63	2017-03-29 15:29:55.961904127 -0500
+++ base-runtime.yaml	2017-03-29 15:08:01.932057403 -0500
@@ -25,6 +25,7 @@
                 - filesystem
                 - glibc-minimal-langpack
                 - libcrypt
+                - make
                 - microdnf
                 - rpm
                 - shadow-utils
$ 
```

After making the above configuration file changes, running the `smoke.py` script results in the following (expected) ERRORs from the new tests:

```
2017-03-29 15:18:18,548 test             L0633 ERROR| ERROR 2-smoke.py:BaseRuntimeSmokeTest.testRequiredPackages -> TestError: Required package 'make' is not installed
```
```
2017-03-29 15:18:20,185 test             L0633 ERROR| ERROR 3-smoke.py:BaseRuntimeSmokeTest.testInstalledPackages -> TestError: Did not expect to have package 'curl' installed
```

@sgallagher Please confirm the test logic is verifying what you expected.

**Comment by bgoncalv** [comment]
This patch will need to be updated once https://github.com/libre-server/baseruntime-docker-tests/pull/16 is merged.

**Comment by bgoncalv** [comment]
I've updated the patch to support the change from #16

**Comment by mmathesius** [comment]
I retested with the new updates using the same process I described earlier. The results are the same. It looks good to me.

**Review by sgallagher — APPROVED** [review]
LGTM

**Pull request merged**
